FROM ubuntu:14.04.5
MAINTAINER Pete Zybrick <pzybrick@gmail.com>

RUN apt-get update \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

 
# JAVA
ARG JAVA_MAJOR_VERSION=8
ARG JAVA_UPDATE_VERSION=162
ENV JAVA_HOME /usr/jdk1.${JAVA_MAJOR_VERSION}.0_${JAVA_UPDATE_VERSION}
ENV PATH $PATH:$JAVA_HOME/bin
add server-jre-${JAVA_MAJOR_VERSION}u${JAVA_UPDATE_VERSION}-linux-x64.tar.gz /usr
RUN  ln -s $JAVA_HOME /usr/java \
  && rm -rf $JAVA_HOME/man \
  && rm -rf server-jre-${JAVA_MAJOR_VERSION}u${JAVA_UPDATE_VERSION}-linux-x64.tar.gz


RUN apt-get update \
 && apt-get -yqq install ssh \
 && apt-get install -y curl unzip \
 && apt-get install -y python3 python3-setuptools \
 && ln -sf /usr/bin/python3 /usr/bin/python \
 && easy_install3 pip py4j \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*     

# http://blog.stuart.axelbrooke.com/python-3-on-spark-return-of-the-pythonhashseed
ENV PYTHONHASHSEED 0
ENV PYTHONIOENCODING UTF-8
ENV PIP_DISABLE_PIP_VERSION_CHECK 1


# copy or download presto here 
ENV PRESTO_VERSION=0.194
ENV PRESTO_HOME=/usr/local/presto
add presto-server-${PRESTO_VERSION}.tar.gz /usr/local
RUN ln -s /usr/local/presto-server-${PRESTO_VERSION} $PRESTO_HOME

# Create data dir
RUN mkdir -p $PRESTO_HOME/data
VOLUME ["$PRESTO_HOME/etc", "$PRESTO_HOME/data"]